### PR TITLE
Fix > Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Serialize\SerializerInterface in vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50

### PR DESCRIPTION
**Pull request by lfluvisotto**
**Fix**

Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Serialize\SerializerInterface in vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50

Error: Cannot instantiate interface Magento\Framework\Serialize\SerializerInterface in vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50

Call Stack:
    0.0006     380888   1. {main}() bin/migrate.php:0
    0.0009     387552   2. require('app/bootstrap.php') bin/migrate.php:8
    0.0133    1103080   3. Magento\Framework\App\Bootstrap::create() app/bootstrap.php:36
    0.0153    1175856   4. Magento\Framework\App\Bootstrap->__construct() vendor/magento/framework/App/Bootstrap.php:123
    0.0153    1175856   5. Magento\Framework\App\ObjectManagerFactory->create() vendor/magento/framework/App/Bootstrap.php:208
    0.0556    2765056   6. Magento\Framework\App\ObjectManager\Environment\Developer->configureObjectManager() vendor/magento/framework/App/ObjectManagerFactory.php:187
    0.0556    2765056   7. Magento\Framework\App\ObjectManager->get() vendor/magento/framework/App/ObjectManager/Environment/Developer.php:70
    0.0556    2765056   8. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() vendor/magento/framework/ObjectManager/ObjectManager.php:70
    0.0562    2783320   9. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
    0.0562    2783320  10. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->resolveArgumentsInRuntime() vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
    0.0562    2783344  11. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->resolveArgument() vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:230
    0.0562    2783344  12. Magento\Framework\App\ObjectManager->get() vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:144
    0.0562    2783344  13. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() vendor/magento/framework/ObjectManager/ObjectManager.php:70
    0.0572    2817000  14. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
    0.0573    2817000  15. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->resolveArgumentsInRuntime() vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
    0.0573    2817400  16. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->resolveArgument() vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:230
    0.0573    2817400  17. Magento\Framework\App\ObjectManager->get() vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:144
    0.0573    2817400  18. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() vendor/magento/framework/ObjectManager/ObjectManager.php:70
    0.0576    2832912  19. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
    0.0576    2833232  20. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->resolveArgumentsInRuntime() vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
    0.0577    2834008  21. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->resolveArgument() vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:230
    0.0577    2834008  22. Magento\Framework\App\ObjectManager->get() vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:144
    0.0577    2834008  23. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() vendor/magento/framework/ObjectManager/ObjectManager.php:70
    0.0577    2835616  24. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
    0.0578    2835616  25. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->resolveArgumentsInRuntime() vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
    0.0578    2836392  26. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->resolveArgument() vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:230
    0.0578    2836392  27. Magento\Framework\App\ObjectManager->get() vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:144
    0.0578    2836392  28. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() vendor/magento/framework/ObjectManager/ObjectManager.php:70
    0.0583    2865760  29. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
    0.0583    2865760  30. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->resolveArgumentsInRuntime() vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
    0.0586    2870680  31. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->resolveArgument() vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:230
    0.0586    2870680  32. Magento\Framework\App\ObjectManager->get() vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:144
    0.0586    2870680  33. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() vendor/magento/framework/ObjectManager/ObjectManager.php:70
    0.0589    2876032  34. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
    0.0589    2876672  35. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->resolveArgumentsInRuntime() vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
    0.0589    2877072  36. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->resolveArgument() vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:230
    0.0589    2877072  37. Magento\Framework\App\ObjectManager->get() vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:144
    0.0590    2877072  38. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() vendor/magento/framework/ObjectManager/ObjectManager.php:70
    0.0765    3775240  39. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->createObject() vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:66
    0.0765    3775624  40. Magento\Framework\App\ResourceConnection\Config->__construct() vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111
    0.0765    3775624  41. Magento\Framework\App\ResourceConnection\Config->__construct() vendor/magento/framework/App/ResourceConnection/Config.php:52
    0.0765    3775624  42. Magento\Framework\App\ObjectManager->get() vendor/magento/framework/Config/Data/Scoped.php:84
    0.0765    3775624  43. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() vendor/magento/framework/ObjectManager/ObjectManager.php:70

### CODE REVIEW

**Comment by sopedro** [comment]
where is the "Fix" ??

**Comment by lfluvisotto** [comment]
In my local environment:

When I cloned the repo > git@github.com:magento/code-migration.git

I executed composer install > Installing magento/framework (101.0.5)

For some reason did come with the folder magento/framework/Serialize (maybe my composer cache did that)

After set composer.json to > "magento/framework": "^101.0",

Folder magento/framework/Serialize was installed.

Then I injected the class in di.xml

<preference for="Magento\Framework\Serialize\SerializerInterface" type="Magento\Framework\Serialize\Serializer\Serialize" />

**Comment by sopedro** [comment]
> In my local environment:
> 
> When I cloned the repo > [git@github.com](mailto:git@github.com):magento/code-migration.git
> 
> I executed composer install > Installing magento/framework (101.0.5)
> 
> For some reason did come with the folder magento/framework/Serialize (maybe my composer cache)
> 
> After set composer.json to > "magento/framework": "^101.0",
> 
> Folder magento/framework/Serialize was installed.
> 
> Then I injected the class in di.xml

Hi, I tried all your steps, and no luck.
The folder is installed, the class was already injected in di.xml by default.
When I ran the script i got the same error.
I'm on php 7.1 in macOs

**Comment by kirmorozov** [comment]
> > In my local environment:
> > When I cloned the repo > [git@github.com](mailto:git@github.com):magento/code-migration.git
> > I executed composer install > Installing magento/framework (101.0.5)
> > For some reason did come with the folder magento/framework/Serialize (maybe my composer cache)
> > After set composer.json to > "magento/framework": "^101.0",
> > Folder magento/framework/Serialize was installed.
> > Then I injected the class in di.xml
> 
> Hi, I tried all your steps, and no luck.
> The folder is installed, the class was already injected in di.xml by default.
> When I ran the script i got the same error.
> I'm on php 7.1 in macOs

Dont forget to run composer update.
This issue is because magento/framework was updated after tool actually worked.

**Comment by JayGajjar** [comment]
I am still facing same issue, after following your steps issue still persists. Can you please help me out ?

**Comment by Domsie1** [comment]
I also deal with this issue, after following the steps the problem remains.

**Comment by func0der** [comment]
@lfluvisotto Why are you closing the issue? Is this fixed somehow? 

I just downloaded the latest development state and it still has the issue.

**Comment by zhartaunik** [comment]
Fix helped me. 
Probably everyone who cannot solve it forgot to:
# clear vendor folder
# clear composer cache and dump-autoload
# run again composer install

**Comment by Mil0dV** [comment]
For me just adding

 <preference for="Magento\Framework\Serialize\SerializerInterface" type="Magento\Framework\Serialize\Serializer\Serialize" />

to app/aetc/di.xml was enough. Not sure why this still isn't merged.

**Pull request closed without merging**
